### PR TITLE
fix(leak): add needed free/delete

### LINKED ISSUE #4: Memory leak
When playing the test video, we can note that there is a memory leak.

It's easily visible when using [VTune](https://software.intel.com/en-us/vtune).
Capture du 2019-10-02 15-55-39

### PR DESCRIPTION
**Pull request by MaXZon3**
This addition fix the memory leak seen in #4.

See VTune results below on the same example video from the original repository.

Before | After
---- | ----
Capture du 2019-10-02 15-55-39 | Capture du 2019-10-02 16-05-28

Fixes #4

### CODE REVIEW

File: src/libchessdetector/non_max_sup_pts.cpp [hunk 1]
```diff
@@ -360,6 +360,8 @@ int non_max_sup_pts(size_t w, size_t h, int16_t image[], int border,
 	// prune the neighbourhood weaklings
 	int culled = cull_neighbourhood(num_found, cp, cn_halfwidth);
 
+	free(*pt_output);
+
 	// allocate storage for the accepted points
 	if (!(*pt_output = new_pt_output(num_found - culled))) {
```
Comment (dweckmann) [inline src/libchessdetector/non_max_sup_pts.cpp:366]: A better fix would be that new_pt_output use realloc instead of malloc. The `free(*pt_output);` would be then unnecessary. Still, I will not block the pull request, but a new issues should be created,

File: src/track_helper.cpp [hunk 2]
```diff
@@ -180,7 +180,7 @@ TrackHelper::TrackHelper (std::string filename) :
 
 TrackHelper::~TrackHelper()
 {
-    if (!tracker)
+    if(tracker)
```
Comment (dweckmann) [inline src/track_helper.cpp]: You can simply remove the `if(tracker)`

File: src/libchessdetector/chess_detector.cpp [hunk 3]
```diff
@@ -32,7 +32,10 @@ ChessDetector::~ChessDetector()
 		m_resp = NULL;
 		m_resp_init = false;
 	}
-
+	if(m_points)
```
Comment (dweckmann) [inline src/libchessdetector/chess_detector.cpp]: you can remove the `if(m_points)`

**Review by dweckmann — CHANGES_REQUESTED** [review]

File: src/libchessdetector/non_max_sup_pts.cpp (hunk 1 above)
Comment (MaXZon3) [reply src/libchessdetector/non_max_sup_pts.cpp:366]: You're right!

The issue was created here : https://github.com/IRCAD-IHU/hybrid_marker_track/issues/6

Feel free to resolve this discussion if it's ok for you. :wink:

File: src/track_helper.cpp (hunk 2 above)
Comment (MaXZon3) [reply src/track_helper.cpp]: Should be fixed here : dbb5a9ad8227d426c79a983b36ea7fec86b957b0

File: src/libchessdetector/chess_detector.cpp (hunk 3 above)
Comment (MaXZon3) [reply src/libchessdetector/chess_detector.cpp]: Should be fixed here : dbb5a9ad8227d426c79a983b36ea7fec86b957b0

**Review by dweckmann — APPROVED** [review]
